import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import { QueryProvider } from "@/lib/components/QueryProvider";
import "./globals.css";

const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={ibmPlexSans.className}>
      <body className="text-body text-default bg-background flex flex-col gap-d items-center justify-start">
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
